### ISSUE TITLE
can't import library 

### ISSUE THREAD

**Issue by jedsada-gh** [jetlinkio/jetlink-android-sdk#1]
compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile('com.veslabs.jetlink:jetlinklibrary:1.1.8@aar'){
        exclude module: 'com.android.support'
        transitive = true
    }
*min sdk 17

i can't import library why ? 

<img width="991" alt="screen shot 2017-03-15 at 9 55 59 am" src="https://cloud.githubusercontent.com/assets/24611167/23931651/ab8c3ed2-0965-11e7-9a1c-aaa611891ac3.png">

**Comment by jedsada-gh** [comment]
compileSdkVersion 25
buildToolsVersion "25.0.2"

targetSdkVersion 25

**Comment by burhanaras** [comment]
Hi, Jetsada. Did you resolve the problem?
Thanks.

**Comment by saintjab** [comment]
Any help on this? JetLinkUser and JetLinkApp imports aren't working for me either.
