### ISSUE TITLE
ChatActivity

### ISSUE THREAD

**Issue by jedsada-gh** [jetlinkio/jetlink-android-sdk#2]
I can't receive message when active chat activity but kill app show FCM when chat on web

Log --->
Data Payload: {message={"MessageId":"592018d3e365b512d06ba107","ConversationId":"59201571e365b52a9c35adfb","FromUserId":"592014b6e365b512d06ba0d1","ToUserId":"58d336e57037e22f4092c751","IsAgent":true,"AvatarUrl":"https://public.jetlink.io/files/img/person.jpg","FromName":"Grab Readcar","MessageText":"Hi","MessageStatus":null,"MessageSource":null,"SendDate":null,"DeliveredDate":null,"SeenDate":null,"MessageType":null,"Payload":null,"IsBot":false,"Content":null,"FileUrl":null,"DisplayFileName":null,"FileType":null,"isHaveBotMessage":null,"HasBotEverAnswered":null,"HasAgentEverAnswered":null}}

**Comment by burhanaras** [comment]
Hi T-Jedsada,

Thanks for notifying us. We have a new version.

Could you plase update your Gradle dependency as follows:

```
    compile('com.veslabs.jetlink:jetlinklibrary:1.1.12@aar') {
        transitive = true
    }
```

Kind Regards,

**Comment by jedsada-gh** [comment]
Thanks a lot
