### ISSUE TITLE
Gradle not working

### ISSUE THREAD

**Issue by AdnanFakhar** [jetlinkio/jetlink-android-sdk#4]
import com.veslabs.jetlinklibrary.JetLinkApp; --- > error

testImplementation 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support:design:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile('com.veslabs.jetlink:jetlinklibrary:1.1.8@aar'){
        exclude module: 'com.android.support'
        transitive = true
    }

**Comment by kaantezgel** [comment]
Hi,

We have updated our Android SDK to v2.0.9. Please update your config file as well. 
Your gradle file should look like such below;

dependencies {
      implementation('org.bitbucket.veslabs:jetlink-android-sdk-v2:2.0.9') {
        transitive = false
    }
}

Please have a look our latest documantaiton on; https://github.com/jetlinkio/jetlink-android-sdk/wiki
